os:
  - linux
  - osx

sudo: false
language: node_js
node_js:
  - "7"
addons:
  apt:
    packages:
      - libxss-dev

install:
  - rm -rf node_modules
  - npm install -g yarn
  - yarn install
  - yarn install --dev
  - yarn test
